BulkyWeb/Areas/Admin/Controllers/CompanyController.cs
using Bulky.DataAccess.Repository.IRepository;
using Bulky.Models;
using Bulky.Utility;
using BulkyWeb.DataAccess.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BulkyWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles =SD.Role_Admin)]
    public class CompanyController : Controller
    {


        private readonly IUnitOfWork _unitOfWork;
        public CompanyController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
           
            return View();
        }



        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Company obj)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.Company.Add(obj);
                _unitOfWork.save();
                TempData["success"] = "Company created successfully";
                return RedirectToAction(nameof(Index));
            }


            return View(obj);
        }

        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            Company companyFromDb = _unitOfWork.Company.Get(u => u.Id == id);
            if (companyFromDb == null)
            {
                return NotFound();
            }
            return View(companyFromDb);

        }


        [HttpPost]
        public IActionResult Edit(Company obj)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.Company.update(obj);
                _unitOfWork.save();
                TempData["success"] = "Company updated successfully";
                return RedirectToAction(nameof(Index));
            }

            return View(obj);

        }


        #region API calls
        [HttpGet]
        public IActionResult GetAll()
        {
            List<Company> companies = _unitOfWork.Company.GetAll().ToList();
            return Json(new {data = companies });
        }

        [HttpDelete]
        public IActionResult Delete(int id)
        {
            Company companyFromObj = _unitOfWork.Company.Get(u=> u.Id == id);
            if (companyFromObj == null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }
            _unitOfWork.Company.Remove(companyFromObj);
            _unitOfWork.save();
            return Json(new { success = true, message = "Delete successfull" });

        }
        #endregion

    }
}

BulkyWeb/Areas/Admin/Views/Company/Create.cshtml
@model Company

<div class="card shadow border-0 mt-4">
    <div class="card-header bg-secondary bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Create Company</h2>
            </div>
        </div>
    </div>

    <div class="card-body p-4">
        <form method="post" class="row">
            <div class="border p-3 mt-4">
                @*<div asp-validation-summary="ModelOnly"></div>*@
                <div class="form-floating py-2 col-12">
                    <input type="text" class="form-control border-0 shadow" asp-for="Name" />
                    <label class="ms-2" asp-for="Name"></label>
                    <span class="text-danger" asp-validation-for="Name"></span>
                </div>
                <div class="form-floating py-2 col-12">
                    <input type="text" class="form-control border-0 shadow" asp-for="PhoneNumber" />
                    <label class="ms-2" asp-for="PhoneNumber"></label>
                    <span class="text-danger" asp-validation-for="PhoneNumber"></span>
                </div>
                <div class="form-floating py-2 col-12">
                    <input type="text" class="form-control border-0 shadow" asp-for="StreetAddress" />
                    <label class="ms-2" asp-for="StreetAddress"></label>
                    <span class="text-danger" asp-validation-for="StreetAddress"></span>
                </div>
                <div class="form-floating py-2 col-12">
                    <input type="text" class="form-control border-0 shadow" asp-for="City" />
                    <label class="ms-2" asp-for="City"></label>
                    <span class="text-danger" asp-validation-for="City"></span>
                </div>
                <div class="form-floating py-2 col-12">
                    <input type="text" class="form-control border-0 shadow" asp-for="State" />
                    <label class="ms-2" asp-for="State"></label>
                    <span class="text-danger" asp-validation-for="State"></span>
                </div>
                <div class="form-floating py-2 col-12">
                    <input type="text" class="form-control border-0 shadow" asp-for="PostalCode" />
                    <label class="ms-2" asp-for="PostalCode"></label>
                    <span class="text-danger" asp-validation-for="PostalCode"></span>
                </div>

                <div class="row mt-3">
                    <div class="col-6 col-md-3">
                        <button type="submit" class="btn btn-primary form-control">Create</button>
                    </div>
                    <div class="col-6 col-md-3">
                        <a asp-controller="Company" asp-action="Index" class="btn btn-outline-primary border form-control">Back to List</a>
                    </div>

                </div>
               
            </div>
        </form>
    </div>


    @section Scripts{
        @{
            <partial name="_ValidationScriptsPartial" />
        }
    }

BulkyWeb/Areas/Admin/Views/Company/Edit.cshtml
@model Company

<div class="card shadow border-0 mt-4">
    <div class="card-header bg-secondary bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Edit Company</h2>
            </div>
        </div>
    </div>

    <div class="card-body p-4">
        <form method="post" class="row">
            <div class="border p-3 mt-4">
                <input asp-for="Id" hidden />
                @*<div asp-validation-summary="ModelOnly"></div>*@
                <div class="form-floating py-2 col-12">
                    <input type="text" class="form-control border-0 shadow" asp-for="Name" />
                    <label class="ms-2" asp-for="Name"></label>
                    <span class="text-danger" asp-validation-for="Name"></span>
                </div>
                <div class="form-floating py-2 col-12">
                    <input type="text" class="form-control border-0 shadow" asp-for="PhoneNumber" />
                    <label class="ms-2" asp-for="PhoneNumber"></label>
                    <span class="text-danger" asp-validation-for="PhoneNumber"></span>
                </div>
                <div class="form-floating py-2 col-12">
                    <input type="text" class="form-control border-0 shadow" asp-for="StreetAddress" />
                    <label class="ms-2" asp-for="StreetAddress"></label>
                    <span class="text-danger" asp-validation-for="StreetAddress"></span>
                </div>
                <div class="form-floating py-2 col-12">
                    <input type="text" class="form-control border-0 shadow" asp-for="City" />
                    <label class="ms-2" asp-for="City"></label>
                    <span class="text-danger" asp-validation-for="City"></span>
                </div>
                <div class="form-floating py-2 col-12">
                    <input type="text" class="form-control border-0 shadow" asp-for="State" />
                    <label class="ms-2" asp-for="State"></label>
                    <span class="text-danger" asp-validation-for="State"></span>
                </div>
                <div class="form-floating py-2 col-12">
                    <input type="text" class="form-control border-0 shadow" asp-for="PostalCode" />
                    <label class="ms-2" asp-for="PostalCode"></label>
                    <span class="text-danger" asp-validation-for="PostalCode"></span>
                </div>

                <div class="row mt-3">
                    <div class="col-6 col-md-3">
                        <button type="submit" class="btn btn-primary form-control">Edit</button>
                    </div>
                    <div class="col-6 col-md-3">
                        <a asp-controller="Company" asp-action="Index" class="btn btn-outline-primary border form-control">Back to List</a>
                    </div>

                </div>

            </div>
        </form>
    </div>


    @section Scripts{
        @{
            <partial name="_ValidationScriptsPartial" />
        }
    }

BulkyWeb/Areas/Admin/Views/Company/Index.cshtml
<div class="card shadow border-0 mt-4">
    <div class="card-header bg-secondary bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Company List</h2>
            </div>
        </div>
    </div>

    <div class="card-body p-4 mb-4">
        <div class="row pt-4">
            <div class="col-6 pb-3">
                <h2 class="text-primary">
                    Company List
                </h2>
            </div>
            <div class="col-6 text-end">
                <a class="btn btn-primary" asp-controller="Company" asp-action="Create"> <i class="bi bi-plus-circle"></i>Create New Company</a>
            </div>
        </div>
        <table id="companytblData" class="table table-striped table-bordered">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Street Address</th>
                    <th>City</th>
                    <th>State</th>
                    <th>Postal Code</th>
                    <th>Phone Number</th>
                    <th></th>
                </tr>
            </thead>
        </table>

    </div>
</div>


@section Scripts{
    <script src="~/js/company.js"></script>
}